// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UserFps.Models;

namespace UserFps.Migrations
{
    [DbContext(typeof(UserContext))]
    partial class UserContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("UserFps.Models.Extra", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateTime");

                    b.Property<string>("JavascriptVer");

                    b.Property<int>("Timezone");

                    b.Property<string>("UserName");

                    b.HasKey("ID");

                    b.ToTable("Extra");
                });

            modelBuilder.Entity("UserFps.Models.LoginRecord", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateTime");

                    b.Property<string>("UserName");

                    b.Property<string>("Vendor1Return");

                    b.Property<string>("Vendor2Return");

                    b.Property<string>("Vendor3Return");

                    b.Property<string>("Vendor4Return");

                    b.Property<string>("Vendor5Return");

                    b.Property<string>("Vendor6Return");

                    b.HasKey("ID");

                    b.ToTable("LoginRecord");
                });

            modelBuilder.Entity("UserFps.Models.Navigator", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AppCodeName");

                    b.Property<string>("AppName");

                    b.Property<string>("AppVersion");

                    b.Property<string>("BuildID");

                    b.Property<bool>("CookieEnabled");

                    b.Property<DateTime>("DateTime");

                    b.Property<string>("Language");

                    b.Property<bool>("Online");

                    b.Property<string>("Oscpu");

                    b.Property<string>("Platform");

                    b.Property<string>("Product");

                    b.Property<string>("SecurityPolicy");

                    b.Property<string>("UserAgent");

                    b.Property<string>("UserName");

                    b.Property<string>("Vendor");

                    b.HasKey("ID");

                    b.ToTable("Navigator");
                });

            modelBuilder.Entity("UserFps.Models.Plugins", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateTime");

                    b.Property<string>("Name");

                    b.Property<string>("UserName");

                    b.Property<string>("VersionNumber");

                    b.HasKey("ID");

                    b.ToTable("Plugins");
                });

            modelBuilder.Entity("UserFps.Models.Screen", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AvailHeight");

                    b.Property<int>("AvailWidth");

                    b.Property<int>("ColorDepth");

                    b.Property<DateTime>("DateTime");

                    b.Property<int>("Height");

                    b.Property<int>("PixelDepth");

                    b.Property<string>("UserName");

                    b.Property<int>("Width");

                    b.HasKey("ID");

                    b.ToTable("Screen");
                });

            modelBuilder.Entity("UserFps.Models.UsersModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DeviceId")
                        .HasColumnName("DeviceID");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false);

                    b.Property<string>("Ioaa");

                    b.Property<string>("Iobb");

                    b.Property<string>("Iocc");

                    b.Property<string>("Iodd");

                    b.Property<string>("Ioee");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false);

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnName("UserName");

                    b.HasKey("ID");

                    b.ToTable("UsersModel");
                });

            modelBuilder.Entity("UserFps.Models.Vendor", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("ServiceActive");

                    b.Property<string>("VendorCode");

                    b.Property<string>("VendorName");

                    b.HasKey("ID");

                    b.ToTable("Vendor");
                });
#pragma warning restore 612, 618
        }
    }
}
